---
# Manual Omarchy VM Installation via Omarchy ISO
#
# This provides simple guidance for interactive installation using the official
# Omarchy ISO, which includes the complete setup wizard and user experience.

- name: Display Omarchy VM Installation Instructions
  ansible.builtin.debug:
    msg: |
      🚀 OMARCHY DEVELOPMENT WORKSTATION

      VM Configuration:
      - VM ID: {{ omarchy_vm.id }}
      - IP Address: {{ omarchy_vm.ip }}
      - CPU Cores: 32 (full AMD Ryzen 9 9950X3D power)
      - Memory: 38GB with balloon memory
      - Storage: 200GB ZFS high-performance storage
      - ISO: Omarchy 3.0.1 (mounted and ready)

      📋 INTERACTIVE INSTALLATION STEPS:

      1. Start VM: make omarchy-start

      2. Connect to Proxmox Web UI:
         → https://{{ ansible_default_ipv4.address | default('192.168.0.19') }}:8006
         → VMs/Containers → VM 101 (omarchy-dev) → Console

      3. Boot from Omarchy ISO (automatic)
         → The VM will boot directly into the Omarchy installation environment

      4. Follow the installation wizard:
         → Set up disk encryption (required for Omarchy)
         → Create your user account
         → Configure system settings

      5. After installation and reboot:
         → System will boot into Omarchy desktop
         → All development tools pre-installed and configured

      6. Optional - Set up Google Remote Desktop:
         → Run: make deploy-vm-omarchy-devmachine --tags remote-desktop
         → Follow the manual steps for Google account authorization

      💡 FEATURES INCLUDED:
      - Arch Linux + Hyprland window manager
      - Complete development environment (VS Code, Git, etc.)
      - High-performance configuration for intensive development
      - Automatic network configuration (192.168.0.101/24)

  when: omarchy_guided_install | default(true)

- name: Configure VM for installation
  block:
    - name: Set boot order for installation
      ansible.builtin.command: >
        qm set {{ omarchy_vm.id }}
        --boot order=ide3;scsi0
      register: boot_order_result
      changed_when: "'update' in boot_order_result.stdout"
      delegate_to: "{{ groups['proxmox'][0] }}"

    - name: Display installation instructions
      ansible.builtin.debug:
        msg: |
          🚀 Omarchy VM Ready for Installation

          VM ID: {{ omarchy_vm.id }}
          IP Address: {{ omarchy_vm.ip }}
          Memory: 38GB (with balloon)
          CPU Cores: 32 (full host power)
          Disk: 200GB ZFS storage

          INSTALLATION STEPS:
          1. Start VM: make omarchy-start (or qm start {{ omarchy_vm.id }})
          2. Connect to console via Proxmox web UI ({{ ansible_default_ipv4.address }}:8006)
          3. Boot from Omarchy ISO (should be automatic)
          4. Follow installation wizard:
             - Enable disk encryption (required for Omarchy)
             - Create user account
             - Configure networking (IP: {{ omarchy_vm.ip }})
          5. After reboot, run: wget -qO- https://omarchy.org/install | bash

          REMOTE DESKTOP:
          - Google Remote Desktop automation available after installation
          - Run: ansible-playbook vm-omarchy-configure.yml --tags remote-desktop

          ALTERNATIVE: Use archinstall config for fully automated base installation