---
# Main tasks for Omarchy Dev VM configuration

- name: Include ISO management tasks
  include_tasks: iso-management.yml
  tags:
    - omarchy
    - iso

- name: Include VM configuration tasks
  include_tasks: vm-configuration.yml
  tags:
    - omarchy
    - configure

- name: Include remote desktop setup
  include_tasks: remote-desktop.yml
  tags:
    - omarchy
    - remote-desktop
  when: remote_desktop_enable | default(true)