---
# Omarchy Development VM Post-Deployment Configuration

- name: Debug VM connection
  debug:
    msg: "Configuring Omarchy VM {{ omarchy_vm_name }} at {{ omarchy_vm_ip }}"

- name: Wait for VM to be ready
  wait_for_connection:
    timeout: 300
  delegate_to: "{{ omarchy_vm_ip }}"

- name: Gather VM facts
  setup:
  delegate_to: "{{ omarchy_vm_ip }}"

- name: Verify Omarchy installation
  command: uname -a
  register: system_info
  delegate_to: "{{ omarchy_vm_ip }}"

- name: Display system information
  debug:
    var: system_info.stdout

- name: Verify Arch Linux system
  command: grep "ID=arch" /etc/os-release
  register: arch_check
  delegate_to: "{{ omarchy_vm_ip }}"

- name: Verify Hyprland is available
  command: which Hyprland
  register: hyprland_check
  delegate_to: "{{ omarchy_vm_ip }}"
  failed_when: false  # Don't fail if not found, just register result

- name: Display Omarchy verification results
  debug:
    msg:
      - "Arch Linux detected: {{ arch_check.stdout != '' }}"
      - "Hyprland available: {{ hyprland_check.rc == 0 }}"

# Placeholder for future configuration tasks
- name: Configure development environment
  debug:
    msg: "Future: Configure development tools and user environment"
  when: false  # Disabled until needed