---
# Template creation tasks for Omarchy

- name: Check if template already exists
  ansible.builtin.command: qm status {{ omarchy_template_id }}
  register: template_status
  failed_when: false
  changed_when: false

- name: Create VM for template if it doesn't exist
  when: template_status.rc != 0
  block:
    - name: Create base VM for template
      ansible.builtin.command: >
        qm create {{ omarchy_template_id }}
        --name {{ omarchy_template_name }}
        --memory {{ omarchy_template.memory }}
        --cores {{ omarchy_template.cores }}
        --sockets 1
        --cpu host
        --net0 virtio,bridge={{ omarchy_template.network_bridge }}
        --scsihw {{ omarchy_template.scsihw }}
        --scsi0 {{ proxmox_vm_storage }}:{{ omarchy_template.disk_size }},discard=on,ssd=1
        --ide2 {{ proxmox_iso_storage }}:iso/{{ omarchy_iso_name }},media=cdrom
        --boot {{ omarchy_template.boot }}
        --ostype {{ omarchy_template.ostype }}
        --bios {{ omarchy_template.bios }}
        --machine {{ omarchy_template.machine }}
        --vga qxl
        --agent 1
      register: vm_created

    - name: Set additional VM options
      ansible.builtin.command: >
        qm set {{ omarchy_template_id }}
        --onboot 0
        --protection 0
        --description "Omarchy (Arch Linux + Hyprland) template VM. Boot from ISO to install."
      when: vm_created.changed

    - name: Add cloud-init drive for network configuration
      ansible.builtin.command: >
        qm set {{ omarchy_template_id }}
        --ide0 {{ proxmox_vm_storage }}:cloudinit
      register: cloudinit_added
      failed_when: false

    - name: Configure cloud-init network settings
      ansible.builtin.command: >
        qm set {{ omarchy_template_id }}
        --ipconfig0 ip=dhcp
        --nameserver {{ omarchy_vm.nameserver }}
        --searchdomain {{ omarchy_vm.searchdomain }}
      when: cloudinit_added.rc == 0

    - name: Display template creation status
      ansible.builtin.debug:
        msg:
          - "Template VM {{ omarchy_template_id }} created successfully"
          - "Manual steps required:"
          - "1. Start VM {{ omarchy_template_id }} from Proxmox console"
          - "2. Complete Omarchy installation"
          - "3. Install cloud-init and qemu-guest-agent in the VM"
          - "4. Shutdown the VM"
          - "5. Convert to template: qm template {{ omarchy_template_id }}"

- name: Check if VM is already a template
  ansible.builtin.command: >
    qm config {{ omarchy_template_id }} | grep -q "^template: 1"
  register: is_template
  failed_when: false
  changed_when: false
  when: template_status.rc == 0

- name: Reminder for template conversion
  ansible.builtin.debug:
    msg:
      - "VM {{ omarchy_template_id }} exists but is not a template"
      - "After OS installation, convert it with: qm template {{ omarchy_template_id }}"
  when:
    - template_status.rc == 0
    - is_template.rc != 0