services:
  homelab-dev:
    build: .
    container_name: homelab-infrastructure
    volumes:
      - .:/workspace
      - ~/.ssh:/tmp/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
      - ANSIBLE_STDOUT_CALLBACK=yaml
    command: tail -f /dev/null
    networks:
      - homelab

networks:
  homelab:
    driver: bridge