---
- name: Configure Omarchy VM after installation
  hosts: proxmox
  gather_facts: no
  vars:
    vm_id: 101
    vm_name: "omarchy-dev"
    vm_ip: "192.168.0.101"

  tasks:
    - name: Check if VM is running
      ansible.builtin.command: qm status {{ vm_id }}
      register: vm_status
      changed_when: false
      failed_when: vm_status.rc != 0

    - name: Ensure VM is running
      ansible.builtin.command: qm start {{ vm_id }}
      when: "'running' not in vm_status.stdout"
      register: vm_start

    - name: Wait for VM to be accessible via network
      ansible.builtin.wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: 300
        delay: 10
      when: vm_start.changed or 'running' in vm_status.stdout

    - name: Install QEMU guest agent in VM (if accessible via qm guest exec)
      ansible.builtin.command: >
        qm guest exec {{ vm_id }} -- bash -c "pacman -Sy --noconfirm qemu-guest-agent && systemctl enable --now qemu-ga"
      register: agent_install
      failed_when: false
      changed_when: agent_install.rc == 0

    - name: Configure VM hardware optimizations
      block:
        - name: Enable QEMU guest agent
          ansible.builtin.command: qm set {{ vm_id }} --agent 1
          register: agent_enable
          changed_when: "'update VM' in agent_enable.stdout"

        - name: Set CPU type to host for better performance
          ansible.builtin.command: qm set {{ vm_id }} --cpu host
          register: cpu_set
          changed_when: "'update VM' in cpu_set.stdout"

        - name: Enable balloon device for dynamic memory
          ansible.builtin.command: qm set {{ vm_id }} --balloon 4096
          register: balloon_set
          changed_when: "'update VM' in balloon_set.stdout"

    - name: Create VM backup schedule (optional)
      ansible.builtin.command: >
        pvesh create /cluster/backup --vmid {{ vm_id }}
        --schedule "sun 02:00"
        --storage local
        --mode snapshot
        --enabled 1
      register: backup_schedule
      failed_when: false
      changed_when: backup_schedule.rc == 0

    - name: Display configuration summary
      ansible.builtin.debug:
        msg:
          - "Omarchy VM (ID: {{ vm_id }}) configuration complete"
          - "IP Address: {{ vm_ip }}"
          - "Access via: ssh user@{{ vm_ip }} or Proxmox console"
          - "Note: Complete Omarchy installation manually if not done"
          - "Documentation: https://omarchy.org/"