---
- name: Setup Omarchy Dev VM template and provisioning
  hosts: proxmox
  gather_facts: no

  roles:
    - role: omarchy-dev-vm
      tags:
        - omarchy
        - always

  tasks:
    - name: Display setup summary
      ansible.builtin.debug:
        msg:
          - "Omarchy VM setup complete"
          - "Template ID: {{ omarchy_template_id | default(9001) }}"
          - "VM ID: {{ omarchy_vm.id | default(101) }}"
          - "Next steps:"
          - "1. If template not created: Start VM {{ omarchy_template_id | default(9001) }} and install Omarchy"
          - "2. After installation: Convert to template with 'qm template {{ omarchy_template_id | default(9001) }}'"
          - "3. Create VMs from template: Run with -e omarchy_create_vm=true"