---
# Omarchy Automated Development VM Setup Playbook
# Two-stage automated installation: Arch Linux + Omarchy
- name: Setup Omarchy Development VM - Automated Installation
  hosts: proxmox
  become: false
  gather_facts: true

  vars_files:
    - configuration-by-ansible/vm-omarchy-dev-automated/defaults/main.yml

  vars:
    # Load configuration from infrastructure catalog
    catalog: "{{ lookup('file', 'infrastructure-catalog.yml') | from_yaml }}"
    vm_config: "{{ catalog.services[102] }}"

  tasks:
    - name: Include cloud image management tasks
      include_tasks: configuration-by-ansible/vm-omarchy-dev-automated/tasks/iso-management.yml
      vars:
        omarchy_vm_automated:
          id: 102
          name: "{{ vm_config.name }}"
          ip: "{{ vm_config.ip }}"
      tags: [download, cloud-image]

    - name: Include cloud-init installation tasks
      include_tasks: configuration-by-ansible/vm-omarchy-dev-automated/tasks/cloud-init-install.yml
      vars:
        omarchy_vm_automated:
          id: 102
          name: "{{ vm_config.name }}"
          ip: "{{ vm_config.ip }}"
      tags: [cloud-init, install]

    - name: Include post-installation verification
      include_tasks: configuration-by-ansible/vm-omarchy-dev-automated/tasks/post-install.yml
      vars:
        omarchy_vm_automated:
          id: 102
          name: "{{ vm_config.name }}"
          ip: "{{ vm_config.ip }}"
      tags: [post-install, verify]

  tags:
    - omarchy-automated
    - vm
    - development