---
- name: Configure Android #19 Proxmox Server - Base Configuration
  hosts: proxmox
  become: yes

  tasks:
    - name: Test connection
      ping:

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "192.168.0.19 proxmox pve"
        - "192.168.0.10 android16-bastion android16"