---
# Terraform Preparation Playbook
# Ensures Proxmox host is ready for Terraform provisioning
- name: Prepare Proxmox for Terraform
  hosts: proxmox
  gather_facts: no

  tasks:
    - name: Check SSH connectivity first
      ping:
      register: ping_result
      ignore_errors: yes

    - name: Display SSH setup instructions if connection fails
      fail:
        msg: |
          ❌ SSH CONNECTION FAILED to Proxmox ({{ ansible_host }})

          To fix this, run these commands on your LOCAL machine:

          1. Generate SSH key (skip if you have one):
             ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

          2. Copy SSH key to Proxmox:
             ssh-copy-id root@{{ ansible_host }}

          3. Test the connection:
             ssh root@{{ ansible_host }} "echo 'SSH working!'"

          4. Retry this command:
             make proxmox-terraform-prep

          For more details, see: docs/SSH_SETUP.md
      when: ping_result is failed

    - name: Gather facts after SSH check
      setup:
      when: ping_result is succeeded
    - name: Update Proxmox template list
      shell: pveam update
      register: template_update
      changed_when: template_update.rc == 0

    - name: Check if Debian 12 template exists
      shell: pveam list local | grep -q "debian-12-standard_12.12-1_amd64.tar.zst"
      register: template_exists
      failed_when: false
      changed_when: false

    - name: Download Debian 12 LXC template if not present
      shell: pveam download local debian-12-standard_12.12-1_amd64.tar.zst
      register: template_download
      changed_when: "'downloaded' in template_download.stdout"
      when: template_exists.rc != 0

    - name: Verify template is available
      shell: pveam list local | grep "debian-12-standard_12.12-1_amd64.tar.zst"
      register: template_verification
      changed_when: false

    - name: Display template status
      debug:
        msg:
          - "✅ Proxmox templates ready for Terraform"
          - "Available template: {{ template_verification.stdout }}"
          - "Terraform can now provision containers using this template"