---
# Test playbook for Omarchy installation approach selection
- name: Test Omarchy Installation Approach Selection
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Default configuration (can be overridden)
    omarchy_installation_method: "{{ install_method | default('manual') }}"
    omarchy_vm:
      id: 101
      ip: "192.168.0.101"
    ansible_default_ipv4:
      address: "192.168.0.19"

  tasks:
    - name: Display Installation Method Configuration
      ansible.builtin.debug:
        msg: |
          🚀 Omarchy VM Installation Configuration

          Selected Method: {{ omarchy_installation_method | upper }}
          {% if omarchy_installation_method == 'manual' %}

          📋 MANUAL INSTALLATION SELECTED
          - Interactive installation via VM console
          - Full control over disk setup and user creation
          - Official Omarchy experience

          {% elif omarchy_installation_method == 'semi-automated' %}

          ⚡ SEMI-AUTOMATED INSTALLATION SELECTED
          - Pre-configured archinstall setup
          - Automated base system installation
          - Manual Omarchy script execution

          {% elif omarchy_installation_method == 'custom' %}

          🤖 CUSTOM AUTOMATION SELECTED (Experimental)
          - Fully automated headless installation
          - No manual intervention required
          - Custom scripting approach

          {% endif %}

    - name: Manual Installation Guidance
      ansible.builtin.debug:
        msg: |
          📋 MANUAL INSTALLATION STEPS:

          1. Start VM: make omarchy-start
          2. Connect to Proxmox Web UI: https://{{ ansible_default_ipv4.address }}:8006
          3. Open VM 101 console
          4. Boot from Omarchy ISO (automatic)
          5. Follow installation wizard:
             - Set up disk encryption (required)
             - Create user account
             - Configure system
          6. After reboot: wget -qO- https://omarchy.org/install | bash
          7. Set up Google Remote Desktop: make deploy-vm-omarchy-devmachine --tags remote-desktop
      when: omarchy_installation_method == 'manual'

    - name: Semi-Automated Installation Steps
      ansible.builtin.debug:
        msg: |
          ⚡ SEMI-AUTOMATED INSTALLATION STEPS:

          1. Start VM: make omarchy-start
          2. Connect to console and boot Arch Linux ISO (not Omarchy ISO)
          3. Configure network: iwctl or dhcpcd
          4. Download config: curl -O https://github.com/your-repo/archinstall-config.json
          5. Run: archinstall --config archinstall-config.json --silent
          6. After reboot and SSH access: wget -qO- https://omarchy.org/install | bash

          Pre-configured features:
          - LUKS disk encryption enabled
          - Hyprland desktop environment
          - Essential packages included
          - Network configured for {{ omarchy_vm.ip }}
      when: omarchy_installation_method == 'semi-automated'

    - name: Custom Automation Status
      ansible.builtin.debug:
        msg: |
          🤖 CUSTOM AUTOMATION STATUS:

          ⚠️  EXPERIMENTAL FEATURE
          This approach requires custom scripting and is not officially supported.
          Consider using semi-automated approach instead.

          Next steps:
          1. Implement custom installation script
          2. Configure serial console automation
          3. Set up headless monitoring
      when: omarchy_installation_method == 'custom'