---
# Ubuntu Desktop VM Post-Installation Playbook
# Configure the VM and install Omakub via QEMU Guest Agent
- name: Post-Install Ubuntu Desktop Development VM
  hosts: proxmox
  become: false
  gather_facts: true

  vars_files:
    - configuration-by-ansible/vm-ubuntu-desktop-devmachine/defaults/main.yml

  vars:
    # Load configuration from infrastructure catalog
    catalog: "{{ lookup('file', 'infrastructure-catalog.yml') | from_yaml }}"
    vm_config: "{{ catalog.services[103] }}"

  tasks:
    - name: Include VM configuration tasks
      include_tasks: configuration-by-ansible/vm-ubuntu-desktop-devmachine/tasks/vm-configure.yml
      tags: [configure, packages]

    - name: Include Omakub installation tasks
      include_tasks: configuration-by-ansible/vm-ubuntu-desktop-devmachine/tasks/omakub-install.yml
      tags: [omakub, install]

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          🎉 Ubuntu Desktop VM post-installation complete!

          ✅ VM configured: {{ vm_config.name }} ({{ vm_config.ip }})
          ✅ Required packages installed
          ✅ Omakub installed and configured

          🖥️  Access the VM via Proxmox console
          🔧 All configuration done via QEMU Guest Agent

  tags:
    - ubuntu-desktop
    - post-install
    - vm
