---
# Check if PCIe ASPM parameter already exists in GRUB configuration

- name: Read current GRUB configuration
  ansible.builtin.slurp:
    src: /etc/default/grub
  register: grub_config

- name: Check if pcie_aspm=off is already configured
  ansible.builtin.set_fact:
    pcie_aspm_configured: "{{ 'pcie_aspm=off' in (grub_config.content | b64decode) }}"

- name: Display PCIe ASPM configuration status
  ansible.builtin.debug:
    msg: "PCIe ASPM parameter {{ 'already configured' if pcie_aspm_configured else 'not configured' }}"
