---
# Main tasks for Proxmox Host Configuration

- name: Pre-flight safety checks
  include_tasks: preflight-checks.yml
  tags:
    - proxmox
    - preflight
    - safety
  when: proxmox_preflight_checks | default(true)

- name: System configuration
  include_tasks: system.yml
  tags:
    - proxmox
    - system

- name: Storage configuration
  include_tasks: storage.yml
  tags:
    - proxmox
    - storage

- name: Network configuration (DISABLED - use network-safe instead)
  include_tasks: network.yml
  tags:
    - proxmox
    - network
  when: false  # Disabled until we can safely configure networking

- name: Safe network configuration
  include_tasks: network-safe.yml
  tags:
    - proxmox
    - network-safe
    - safety

- name: Template management
  include_tasks: templates.yml
  tags:
    - proxmox
    - templates

- name: API token configuration
  include_tasks: api-tokens.yml
  tags:
    - proxmox
    - api

- name: Backup configuration
  include_tasks: backup.yml
  tags:
    - proxmox
    - backup
  when: proxmox_backup.enabled | default(true)