---
# Main tasks for Proxmox Host Configuration

- name: Pre-flight safety checks
  include_tasks: preflight-checks.yml
  tags:
    - proxmox
    - preflight
    - safety
  when: proxmox_preflight_checks | default(true)

- name: System configuration
  include_tasks: system.yml
  tags:
    - proxmox
    - system

- name: PCIe ASPM GRUB configuration
  include_tasks: grub-pcie-aspm.yml
  tags:
    - proxmox
    - grub
    - pcie-aspm

- name: Storage configuration
  include_tasks: storage.yml
  tags:
    - proxmox
    - storage

# Network configuration is handled by Proxmox installation
# No need to manage bridges - they're created automatically during Proxmox setup

- name: Template management
  include_tasks: templates.yml
  tags:
    - proxmox
    - templates

- name: Cloud image templates
  include_tasks: cloud-image-templates.yml
  tags:
    - proxmox
    - cloud-templates
  when: cloud_template_vm_id is defined

- name: API token configuration
  include_tasks: api-tokens.yml
  tags:
    - proxmox
    - api

- name: Backup configuration
  include_tasks: backup.yml
  tags:
    - proxmox
    - backup
  when: proxmox_backup.enabled | default(true)

- name: RGB/LED light control
  include_tasks: rgb-control.yml
  tags:
    - proxmox
    - rgb
    - hardware
  when: rgb_lights_enabled | default(false)