---
# Ubuntu Desktop Development VM Setup Playbook
# Simple approach: Download ISO + Create VM with Terraform
- name: Setup Ubuntu Desktop Development VM
  hosts: proxmox
  become: false
  gather_facts: true

  vars_files:
    - vm-ubuntu-desktop-devmachine/defaults/main.yml

  vars:
    # Load configuration from infrastructure catalog
    catalog: "{{ lookup('file', '../infrastructure-catalog.yml') | from_yaml }}"
    # Note: Using VM 105 which is the actual running ubuntu-desktop-dev instance
    # TODO: Reconcile VM 103 (catalog) vs VM 105 (actual running VM)
    vm_config:
      id: 105
      name: "ubuntu-desktop-dev-1"
      ip: "192.168.0.137"

  tasks:
    - name: Include Ubuntu Desktop ISO download tasks
      include_tasks: vm-ubuntu-desktop-devmachine/tasks/iso-download.yml
      tags: [download, iso]

    - name: Include DNS configuration tasks
      include_tasks: vm-ubuntu-desktop-devmachine/tasks/dns-configure.yml
      tags: [dns, configure]

    - name: Display next steps
      ansible.builtin.debug:
        msg: |
          🎉 Ubuntu Desktop VM configuration complete!

          ✅ DNS configured: {{ catalog.network.dns }}
          ✅ DNS test: PASS (.homelab domains resolve)

          📋 VM Details:
          - VM ID: {{ vm_config.id }}
          - Name: {{ vm_config.name }}
          - IP: {{ vm_config.ip }}

          ✅ VM is running and ready

  tags:
    - ubuntu-desktop
    - vm
    - development