---
# SSH Connection Check Playbook
# This playbook tests SSH connectivity and provides helpful error messages

- name: Check SSH connectivity to all hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Test SSH connection
      ping:
      register: ping_result
      ignore_errors: yes

    - name: Display success message
      debug:
        msg: "✅ SSH connection successful to {{ inventory_hostname }} ({{ ansible_host }})"
      when: ping_result is succeeded

    - name: Display SSH setup instructions on failure
      debug:
        msg: |
          ❌ SSH CONNECTION FAILED to {{ inventory_hostname }} ({{ ansible_host }})

          To fix this issue, run the following commands on your LOCAL machine:

          1. Generate SSH key (if you don't have one):
             ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

          2. Copy SSH key to the target host:
             ssh-copy-id {{ ansible_user }}@{{ ansible_host }}

          3. Test the connection:
             ssh {{ ansible_user }}@{{ ansible_host }} "echo 'SSH working!'"

          4. Rebuild Docker container and retry:
             docker compose down && docker compose up -d --build
             make test-ping-{{ group_names[0] if group_names else 'all' }}

          For detailed instructions, see: docs/SSH_SETUP.md
      when: ping_result is failed

    - name: Fail with helpful message
      fail:
        msg: |
          SSH setup required for {{ inventory_hostname }}.
          Run: ssh-copy-id {{ ansible_user }}@{{ ansible_host }}
          See docs/SSH_SETUP.md for details.
      when: ping_result is failed