---
# Configure Container After Terraform Provisioning
# This playbook configures containers created by Terraform

- name: Configure containers from infrastructure catalog
  hosts: proxmox
  vars:
    catalog_file: "{{ playbook_dir }}/../../android-19-proxmox/infrastructure-catalog.yml"

  tasks:
    - name: Load infrastructure catalog
      include_vars: "{{ catalog_file }}"

    - name: Get Terraform-managed containers
      set_fact:
        terraform_containers: "{{ services | dict2items | selectattr('value.provisioner', 'defined') | selectattr('value.provisioner', 'equalto', 'terraform') | list }}"

    - name: Configure each Terraform container
      include_tasks: tasks/configure-single-container.yml
      loop: "{{ terraform_containers }}"
      loop_control:
        loop_var: container_item
      vars:
        container_id: "{{ container_item.key }}"
        container_ip: "{{ container_item.value.ip }}"
        container_name: "{{ container_item.value.name }}"

    - name: Display summary of configured containers
      debug:
        msg:
          - "🎉 All Terraform containers configured successfully!"
          - "======================================================="
          - "Configured containers: {{ terraform_containers | map(attribute='value.name') | list | join(', ') }}"
          - ""
          - "Test connectivity:"
          - "{% for item in terraform_containers %}  curl http://{{ item.value.ip }}  # {{ item.value.name }}{% endfor %}"