---
- name: Configure Android #16 Bastion Host
  hosts: bastion

  tasks:
    - name: Test connection
      ping:

    - name: Set hostname
      hostname:
        name: android16-bastion
      become: yes