---
# Configure GRUB to enable IOMMU passthrough

- name: Add IOMMU parameters to GRUB configuration
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*)"$'
    replace: '\1 amd_iommu=on iommu=pt"'
  when: not iommu_grub_configured

- name: Display GRUB configuration status
  ansible.builtin.debug:
    msg: "IOMMU parameters added to GRUB. Run 'update-grub' and reboot to apply."
  when: not iommu_grub_configured
