---
# GPU Passthrough Configuration Tasks

- name: Validate AMD CPU prerequisite
  include_tasks: validate-amd-cpu.yml
  tags: [gpu, validate, iommu]

- name: Check IOMMU runtime status
  include_tasks: check-iommu-runtime.yml
  tags: [gpu, iommu, check]

- name: Check IOMMU GRUB configuration
  include_tasks: check-iommu-grub.yml
  tags: [gpu, iommu, check]

- name: Backup GRUB configuration
  include_tasks: backup-grub-config.yml
  when: not iommu_grub_configured
  tags: [gpu, iommu, backup]

- name: Configure GRUB IOMMU parameters
  include_tasks: configure-grub-iommu.yml
  when: not iommu_grub_configured
  tags: [gpu, iommu, configure]
  register: grub_config_changed

- name: Update GRUB bootloader
  include_tasks: update-grub.yml
  when: grub_config_changed is changed
  tags: [gpu, iommu, update]

- name: Reboot system to apply IOMMU configuration
  include_tasks: reboot-system.yml
  when: grub_config_changed is changed and not iommu_runtime_enabled
  tags: [gpu, iommu, reboot]

- name: Configure VFIO kernel modules
  include_tasks: configure-vfio-modules.yml
  tags: [gpu, vfio, modules]

- name: Identify NVIDIA GPU
  include_tasks: identify-gpu.yml
  tags: [gpu, identify]
