---
# Manual Omakub VM Installation via Ubuntu Desktop ISO
#
# This provides simple guidance for interactive installation using the official
# Ubuntu Desktop ISO, which includes the complete setup wizard and user experience.

- name: Display Omakub VM Installation Instructions
  ansible.builtin.debug:
    msg: |
      🚀 OMAKUB DEVELOPMENT WORKSTATION

      VM Configuration:
      - VM ID: {{ omakub_vm.id }}
      - IP Address: {{ omakub_vm.ip }}
      - CPU Cores: {{ omakub_vm_cores }} (high-performance for development)
      - Memory: {{ omakub_vm_balloon // 1024 }}GB with balloon memory
      - Storage: {{ omakub_vm_disk_size }}GB ZFS high-performance storage
      - ISO: Ubuntu 24.04.1 Desktop (mounted and ready)

      📋 INTERACTIVE INSTALLATION STEPS:

      1. Start VM: make omakub-start

      2. Connect to Proxmox Web UI:
         → https://{{ ansible_default_ipv4.address | default('192.168.0.19') }}:8006
         → VMs/Containers → VM {{ omakub_vm.id }} ({{ omakub_vm.name }}) → Console

      3. Boot from Ubuntu Desktop ISO (automatic)
         → The VM will boot directly into the Ubuntu installation environment

      4. Follow the Ubuntu installation wizard:
         → Choose "Install Ubuntu"
         → Set up user account: {{ ubuntu_user }}/{{ ubuntu_password }}
         → Configure system settings
         → Install GNOME desktop environment

      5. After installation and first boot:
         → Set screen resolution to 1920x1080 and scaling to 200%
         → Open terminal (Ctrl+Alt+T)
         → Run: wget -qO- https://omakub.org/install | bash
         → Approve 4 GNOME extension confirmations
         → Log out and log back in

      6. System will then have:
         → Complete Ubuntu 24.04 desktop environment
         → All Omakub development tools pre-installed and configured

      💡 FEATURES INCLUDED AFTER OMAKUB:
      - Alacritty terminal with Zellij (multiple panes/sessions)
      - Neovim (LazyVim) + VS Code editors
      - Chrome browser, Spotify, Zoom, 1Password
      - Modern CLI tools: eza, fzf, rg, zoxide, bg
      - Automatic network configuration ({{ omakub_vm.ip }}/24)

  when: omakub_guided_install | default(true)

- name: Configure VM for installation
  block:
    - name: Set boot order for installation
      ansible.builtin.command: >
        qm set {{ omakub_vm.id }}
        --boot order=ide2;scsi0
      register: boot_order_result
      changed_when: "'update' in boot_order_result.stdout"
      delegate_to: "{{ groups['proxmox'][0] }}"

    - name: Display installation instructions
      ansible.builtin.debug:
        msg: |
          🚀 Omakub VM Ready for Installation

          VM ID: {{ omakub_vm.id }}
          IP Address: {{ omakub_vm.ip }}
          Memory: {{ omakub_vm_balloon // 1024 }}GB (with balloon)
          CPU Cores: {{ omakub_vm_cores }} (optimized for development)
          Disk: {{ omakub_vm_disk_size }}GB ZFS storage

          INSTALLATION STEPS:
          1. Start VM: make omakub-start (or qm start {{ omakub_vm.id }})
          2. Connect to console via Proxmox web UI ({{ ansible_default_ipv4.address }}:8006)
          3. Boot from Ubuntu Desktop ISO (should be automatic)
          4. Follow Ubuntu installation wizard:
             - Choose "Install Ubuntu"
             - Create user account: {{ ubuntu_user }}
             - Set password: {{ ubuntu_password }}
             - Configure networking (IP: {{ omakub_vm.ip }})
          5. After first boot and desktop setup:
             - Set resolution to 1920x1080, scaling 200%
             - Open terminal: Ctrl+Alt+T
             - Run: wget -qO- https://omakub.org/install | bash
             - Approve GNOME extension confirmations
             - Log out and back in

          🎯 EXPECTED RESULT:
          - Full Ubuntu 24.04 desktop with GNOME
          - Complete Omakub development environment
          - All modern development tools configured
          - Ready for immediate development work

          ⚠️  IMPORTANT NOTES:
          - Omakub requires Ubuntu 24.04+ with GNOME desktop
          - Installation is semi-interactive (requires user confirmations)
          - Total time: ~45-60 minutes (including Ubuntu install)
          - Automatic network configuration via DHCP